apiVersion: v1
kind: Service
metadata:
  name: agent
  namespace: shiritori-agent
spec:
  selector:
    app: agent
  ports:
    - name: http
      port: 8001
      targetPort: http
      nodePort: 31080
  type: NodePort
